### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by 1oglop1**
Please vote which logo you like the most.
Add 👍 to one you like.

https://github.com/PyAmsterdam/py-meetups/tree/logo

### CODE REVIEW

**Comment by 1oglop1** [comment]
1

**Comment by 1oglop1** [comment]
2

**Comment by 1oglop1** [comment]
3

**Comment by 1oglop1** [comment]
4

**Comment by 1oglop1** [comment]
5

**Comment by 1oglop1** [comment]
6

**Comment by tams** [comment]
5 :metal:

**Comment by vlabakje** [comment]
6

**Comment by vojtekb** [comment]
5 appears to be the winner. Let's make it the logo then!

**Pull request closed without merging**
