### PR TITLE
add talk proposal

### PR DESCRIPTION
**Pull request by tomasmor42**

### CODE REVIEW

**Comment by 1oglop1** [comment]
Hi @tomasmor42 It sounds very interesting!
Would you like ti to present on September 19th?

PS. could you please adapt your proposal to this template?
https://github.com/PyAmsterdam/py-meetups/blob/master/resources/_org_examples/talks/example-talk.rst

**Comment by tomasmor42** [comment]
@1oglop1 Done! 
Yes, if you have slots in September.

**Comment by 1oglop1** [comment]
Thank you for the update!
So far yes, we have 3 slots planned.
+ I had to suddenly change event date from 19th to Sep 26th. 
Is that still fine with you?

**Comment by tomasmor42** [comment]
26 works for me as well.

**Pull request merged**
