### PR TITLE
adds 'bridging-dev-ops-gap-with-python' talk proposal

### PR DESCRIPTION
**Pull request by ivica-k**

### CODE REVIEW

**Comment by 1oglop1** [comment]
It looks quite interesting!

**Comment by ivica-k** [comment]
Does this means that the talk is accepted?

**Comment by 1oglop1** [comment]
@ivica-k It LGTM, we are currently working on to make CFP process simpler.
I would like to have this talk on one of PyAmsterdam meetups.
But I'm not yet sure about the date.
@gilgamezh What do you think about the proposal?

**Comment by ivica-k** [comment]
The talk doesn't have to be accepted for the next meetup, it is happening tomorrow and it's a pretty short notice.

**Comment by 1oglop1** [comment]
@ivica-k Hi Ivica, I think we could schedule the talk in March or April, how does that look for you?

**Comment by ivica-k** [comment]
Hey @1oglop1, sure, both March and April sound good to me. There is a possibility that the company I work for would host this; I've reached out to you on LinkedIn.

**Pull request merged**
