### PR TITLE
using micropython in IOT devices

### PR DESCRIPTION
**Pull request by ChefsSlaad**
a talk on the micropython language and my experience using it.

### CODE REVIEW

**Comment by 1oglop1** [comment]
Hi @marcwagner! Thank you for submitting your talk!
We have just received confirmation for our next event in November 13th!
Are you available on that date?

**Comment by ChefsSlaad** [comment]
unfortunately not. I will be attending the homeassistant meetup @ING on that date

**Comment by gilgamezh** [comment]
oh! ok. next time!

**Comment by ChefsSlaad** [comment]
Would love to. Sorry I cannot attend.

**Comment by 1oglop1** [comment]
@marcwagner Let us know when would you like to present.

**Comment by ChefsSlaad** [comment]
Probably at the Meetup after this one. Is it scheduled yet?

**Comment by gilgamezh** [comment]
@marcwagner we are discussing dates. I'll let you know as soon as possible

**Comment by vojtekb** [comment]
Hi Marc,
 would you be available to give the talk 07 Dec, between 10:00 - 14:00 ?

**Comment by ChefsSlaad** [comment]
I am. Still need to do some work if I want to give a live demo though :) I
will get cracking

**Comment by ChefsSlaad** [comment]
I will be able to present on December 7th.

**Comment by vojtekb** [comment]
Cool, adding you to the speakers list

**Comment by ChefsSlaad** [comment]
I see the schedule on meetup.com has not been updated yet.

Will this happen?

**Comment by vojtekb** [comment]
Done!

**Pull request merged**
